### ISSUE TITLE
 No such file or directory: '/scratch/zl3958/VLPR/net_220.pth'

### ISSUE THREAD

**Issue by hiredd** [ZonglinL/ConsecutiveBrownianBridge#2]
No such file or directory: '/scratch/zl3958/VLPR/net_220.pth'

**Comment by ZonglinL** [comment]
Sorry for the delay. You need to change load_VFI to None (leave it as empty) in the config file. Another way to solve it is to download the model weights of VFIformer from https://drive.google.com/drive/folders/140bDl6LXPMlCqG8DZFAXB3IBCvZ7eWyv and set the load_VFI to be the path of the downloaded weights
