### ISSUE TITLE
No module named 'runners'

### ISSUE THREAD

**Issue by zijieloooooou** [ZonglinL/ConsecutiveBrownianBridge#3]
<img width="900" alt="image" src="https://github.com/ZonglinL/ConsecutiveBrownianBridge/assets/46393405/12075b0c-5e4b-4364-8c2f-98946d94393c">

**Comment by ZonglinL** [comment]
Please remove the get_runner in the import line. Runners will be provided when the paper is accepted, and it is not used in this file. Sorry for the confusion

**Comment by ZonglinL** [comment]
You should also comment line 6 in the utils.py  Apologize for that, this is because we did not provide training codes.
