### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by ROTTK** [ZonglinL/ConsecutiveBrownianBridge#4]
Thank you very much for the open source code, it's a very interesting work!
It is claimed that "VFI requires that repeated sampling returns identical results, which is the ground truth intermediate frame."
Why does VFI require identical results?

**Comment by ZonglinL** [comment]
Here are two ways you can understand:

1. If you have a 120 fps video and down sample it to 10 fps. Now, if you want to reconstruct the 120 fps version, then this is the strict ground truth. It is similar to an autoencoder but in a temporal way.
2. When you generate "an image of a cat" (even if you specify what types, what poses, etc), there are many possible solutions: how large the eye is? how big the paw is? However, in VFI, everything is fixed. You cannot change the color, pose, and the size of paw of that cat.

The results do not need to be strictly identical: you can have one pixel in the eye of that cat to be a +1 to the ground truth -- this does not change the visual effect. But we want the variance as small as possible -- we do not want the size of the paw being changed.

**Comment by ROTTK** [comment]
Thank you for your reply!
Could you please explain how much damage the diversity of generated models would do to the VFI task?
I have noticed the Figure 5 in the ablation studies, which shows that the results produced after applying the Brownian bridge diffusion feature less overlapping. But this seems like it has less to do with changing poses, colors, and sizes as you mentioned, and more to do with the new decoder.
Additionally, I also have questions about the ablation studies in the paper.
In my understanding, your paper proposes Brownian Bridge diffusion (denoted as BB) and a new decoder, so there should be four method to compare:
(1) without BB, with old decoder, denoted as LDMVFI in Table 2
(2) without BB, with new decoder
(3) with BB, with old decoder, denoted as LDMVFI + BB in Table 2
(4) with BB, with new decoder, denoted as ours in Table 2
But where is the (2), I didn't find it in you paper, which is crucial to demonstrate that both the BB and the new decoder contribute to the performance improvement, not just the new decoder.
Thanks again for your patience!

**Comment by ZonglinL** [comment]
The poses etc are just for you to understand why low variance is preferred. We want the sampling to be deterministic.

(2) is not provided because comparing (3) and LDMVFI is sufficient to know advantage of the diffusion.

**Comment by ROTTK** [comment]
Thank you for your reply!
